name: BiospherePlugin
main: biosphere.BiospherePlugin
version: 0.0.2
commands:
  biosphere:
    description: Generates biosphere world.
    usage: /biosphere name
  biome:
    description: Shows current biome in biosphere world.
    usage: /biome
  test:
    description: Just temporary command
    usage: /test
